### ISSUE TITLE
More feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-reactive-rest-client#53]
If I am not mistaken, the focus of this guide should be on creating a reactive REST client using what is available through JAX-RS API out of the box and then, using it with a third-party library.

- Revise the Intro i.e. "What you'll learn" section to be more concise and better reflect the focus of the guide and what users will learn.
  - Remove the 2 "What is" sub-sections.  In their current form, they make the guide more difficult to follow than add to it;
  - Simply introduce reactive JAX-RS client, its benefits, why the users will learn, what is the app used and that can be it.

- Ensure that the section titles reflect what the users will accomplish in the sections: Create a reactive JAX-RS client, Use a third-party reactive library with a JAX-RS client, Update the REST service to use the reactive JAX-RS client.

- Each section should focus on what users should be accomplishing and hone in on aspects relevant to reactive JAX-RS client.

The guide title and abstract look fine though the front matter needs work.  I will file a PR for that.

Copy @lauracowen in case she has additional thoughts.  FYI, @gkwan-ibm.

**Comment by TiagoF99** [comment]
Based on feedback given by Gilbert yesterday afternoon, these points should also be mostly addressed by this pr https://github.com/OpenLiberty/draft-guide-jax-rs-reactive-client/pull/52 and can be verified here http://lgdev1.fyre.ibm.com:4020/guides/reactive-rest-client.html

**Comment by yeekangc** [comment]
> Creating a web client using the default JAX-RS API
> Updating the web client to use third-party reactive libraries
> Updating the REST resource to support the reactive JAX-RS client

The latest revised section titles noted above are much clearer.  Then, they are still somewhat inconsistent in the use of "web client" vs "JAX-RS client"?

**Comment by TiagoF99** [comment]
what do you think if we update the last one to `Updating the REST resource to support the reactive JAX-RS web client`?
